### ISSUE TITLE
Does this work with source-map-support?

### ISSUE THREAD

**Issue by vjpr** [inikulin/callsite-record#3]
Looking at the `longjohn` module it seems you need to add something like: `sourceMap.wrapCallSite()`.

**Comment by vjpr** [comment]
My bad, I was running it in a transpiled file which did not load it before all the requires.

**Comment by vjpr** [comment]
Actually, it does not seem to solve my issue. Would it be possible to allow passing in a filename to render instead of allowing only an error?

**Comment by inikulin** [comment]
Works perfectly for me using [source map support package](https://www.npmjs.com/package/source-map-support) and Babel-transpiled code with `retainLines` option set to `true`.

**Comment by inikulin** [comment]
> Would it be possible to allow passing in a filename to render instead of allowing only an error?

This functionality is not supported currently, but can be easily implemented. PR is welcome.

**Comment by inikulin** [comment]
Should be solved with [processFrameFn](https://github.com/inikulin/callsite-record#createcallsiterecord-byfunctionname-typename-processframefn---callsiterecord) option
